version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: commerce
      POSTGRES_DB: commerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://commerce:commerce@db:5432/commerce
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000/api
    ports:
      - "3000:3000"

volumes:
  pgdata: