FROM node:20-alpine

WORKDIR /app

COPY apps/web/package.json ./package.json
RUN npm install

COPY apps/web ./

ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]